site_name: fanzVOUCHER
nav:
  - Home: index.md
  - API: /documentation/
theme:
  name: material
  palette:
    primary: teal
copyright: Copyright &copy; 2024 Fanz GmbH
extra:
  generator: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences