site_name: fanzVOUCHER
site_url: https://fanz-io.github.io/voucher-documentation
nav:
  - Architecture: /arch/
  - API: /documentation/
theme:
  name: material
  font:
    text: IBM Plex Sans
  palette:
    primary: teal
copyright: Copyright &copy; 2024 Fanz GmbH
extra:
  generator: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences