site_name: fanzVOUCHER
site_url: https://fanz-io.github.io/voucher-documentation
nav:
  - Usage: usage/
  - Architecture: arch/
  - API: api/
theme:
  name: material
  font:
    text: IBM Plex Sans
  palette:
    primary: teal
  features:
    - content.code.copy
copyright: Copyright &copy; 2024 Fanz GmbH
extra:
  generator: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - include-markdown:
      encoding: ascii
      preserve_includer_indent: false
      dedent: false
      trailing_newlines: true
      comments: true
      rewrite_relative_urls: true
      heading_offset: 0
      start: <!--start-->
      end: <!--end-->